//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try font.validate()
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 7 colors.
  struct color {
    /// Color `AppColor`.
    static let appColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "AppColor")
    /// Color `CTBlack`.
    static let ctBlack = Rswift.ColorResource(bundle: R.hostingBundle, name: "CTBlack")
    /// Color `CTBlue`.
    static let ctBlue = Rswift.ColorResource(bundle: R.hostingBundle, name: "CTBlue")
    /// Color `CTGray`.
    static let ctGray = Rswift.ColorResource(bundle: R.hostingBundle, name: "CTGray")
    /// Color `CTOrange`.
    static let ctOrange = Rswift.ColorResource(bundle: R.hostingBundle, name: "CTOrange")
    /// Color `CTPurple`.
    static let ctPurple = Rswift.ColorResource(bundle: R.hostingBundle, name: "CTPurple")
    /// Color `CTWhite`.
    static let ctWhite = Rswift.ColorResource(bundle: R.hostingBundle, name: "CTWhite")
    
    /// `UIColor(named: "AppColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func appColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.appColor, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "CTBlack", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func ctBlack(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.ctBlack, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "CTBlue", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func ctBlue(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.ctBlue, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "CTGray", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func ctGray(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.ctGray, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "CTOrange", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func ctOrange(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.ctOrange, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "CTPurple", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func ctPurple(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.ctPurple, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "CTWhite", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func ctWhite(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.ctWhite, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 9 files.
  struct file {
    /// Resource file `Config.plist`.
    static let configPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "Config", pathExtension: "plist")
    /// Resource file `SIL Open Font License.txt`.
    static let silOpenFontLicenseTxt = Rswift.FileResource(bundle: R.hostingBundle, name: "SIL Open Font License", pathExtension: "txt")
    /// Resource file `birds-0.mp3`.
    static let birds0Mp3 = Rswift.FileResource(bundle: R.hostingBundle, name: "birds-0", pathExtension: "mp3")
    /// Resource file `birds-1.mp3`.
    static let birds1Mp3 = Rswift.FileResource(bundle: R.hostingBundle, name: "birds-1", pathExtension: "mp3")
    /// Resource file `piano.wav`.
    static let pianoWav = Rswift.FileResource(bundle: R.hostingBundle, name: "piano", pathExtension: "wav")
    /// Resource file `space-0.mp3`.
    static let space0Mp3 = Rswift.FileResource(bundle: R.hostingBundle, name: "space-0", pathExtension: "mp3")
    /// Resource file `space-1.mp3`.
    static let space1Mp3 = Rswift.FileResource(bundle: R.hostingBundle, name: "space-1", pathExtension: "mp3")
    /// Resource file `water-0.mp3`.
    static let water0Mp3 = Rswift.FileResource(bundle: R.hostingBundle, name: "water-0", pathExtension: "mp3")
    /// Resource file `water-1.mp3`.
    static let water1Mp3 = Rswift.FileResource(bundle: R.hostingBundle, name: "water-1", pathExtension: "mp3")
    
    /// `bundle.url(forResource: "Config", withExtension: "plist")`
    static func configPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.configPlist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "SIL Open Font License", withExtension: "txt")`
    static func silOpenFontLicenseTxt(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.silOpenFontLicenseTxt
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "birds-0", withExtension: "mp3")`
    static func birds0Mp3(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.birds0Mp3
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "birds-1", withExtension: "mp3")`
    static func birds1Mp3(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.birds1Mp3
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "piano", withExtension: "wav")`
    static func pianoWav(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.pianoWav
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "space-0", withExtension: "mp3")`
    static func space0Mp3(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.space0Mp3
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "space-1", withExtension: "mp3")`
    static func space1Mp3(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.space1Mp3
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "water-0", withExtension: "mp3")`
    static func water0Mp3(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.water0Mp3
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "water-1", withExtension: "mp3")`
    static func water1Mp3(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.water1Mp3
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 28 fonts.
  struct font: Rswift.Validatable {
    /// Font `MuseoSans-100Italic`.
    static let museoSans100Italic = Rswift.FontResource(fontName: "MuseoSans-100Italic")
    /// Font `MuseoSans-100`.
    static let museoSans100 = Rswift.FontResource(fontName: "MuseoSans-100")
    /// Font `MuseoSans-300Italic`.
    static let museoSans300Italic = Rswift.FontResource(fontName: "MuseoSans-300Italic")
    /// Font `MuseoSans-300`.
    static let museoSans300 = Rswift.FontResource(fontName: "MuseoSans-300")
    /// Font `MuseoSans-500Italic`.
    static let museoSans500Italic = Rswift.FontResource(fontName: "MuseoSans-500Italic")
    /// Font `MuseoSans-500`.
    static let museoSans500 = Rswift.FontResource(fontName: "MuseoSans-500")
    /// Font `MuseoSans-700Italic`.
    static let museoSans700Italic = Rswift.FontResource(fontName: "MuseoSans-700Italic")
    /// Font `MuseoSans-700`.
    static let museoSans700 = Rswift.FontResource(fontName: "MuseoSans-700")
    /// Font `MuseoSans-900Italic`.
    static let museoSans900Italic = Rswift.FontResource(fontName: "MuseoSans-900Italic")
    /// Font `MuseoSans-900`.
    static let museoSans900 = Rswift.FontResource(fontName: "MuseoSans-900")
    /// Font `Oswald-Demi-BoldItalic`.
    static let oswaldDemiBoldItalic = Rswift.FontResource(fontName: "Oswald-Demi-BoldItalic")
    /// Font `Oswald-DemiBold`.
    static let oswaldDemiBold = Rswift.FontResource(fontName: "Oswald-DemiBold")
    /// Font `Oswald-LightItalic`.
    static let oswaldLightItalic = Rswift.FontResource(fontName: "Oswald-LightItalic")
    /// Font `Oswald-Light`.
    static let oswaldLight = Rswift.FontResource(fontName: "Oswald-Light")
    /// Font `Oswald-RegularItalic`.
    static let oswaldRegularItalic = Rswift.FontResource(fontName: "Oswald-RegularItalic")
    /// Font `Oswald-Regular`.
    static let oswaldRegular = Rswift.FontResource(fontName: "Oswald-Regular")
    /// Font `SourceSansPro-BlackIt`.
    static let sourceSansProBlackIt = Rswift.FontResource(fontName: "SourceSansPro-BlackIt")
    /// Font `SourceSansPro-Black`.
    static let sourceSansProBlack = Rswift.FontResource(fontName: "SourceSansPro-Black")
    /// Font `SourceSansPro-BoldIt`.
    static let sourceSansProBoldIt = Rswift.FontResource(fontName: "SourceSansPro-BoldIt")
    /// Font `SourceSansPro-Bold`.
    static let sourceSansProBold = Rswift.FontResource(fontName: "SourceSansPro-Bold")
    /// Font `SourceSansPro-ExtraLightIt`.
    static let sourceSansProExtraLightIt = Rswift.FontResource(fontName: "SourceSansPro-ExtraLightIt")
    /// Font `SourceSansPro-ExtraLight`.
    static let sourceSansProExtraLight = Rswift.FontResource(fontName: "SourceSansPro-ExtraLight")
    /// Font `SourceSansPro-It`.
    static let sourceSansProIt = Rswift.FontResource(fontName: "SourceSansPro-It")
    /// Font `SourceSansPro-LightIt`.
    static let sourceSansProLightIt = Rswift.FontResource(fontName: "SourceSansPro-LightIt")
    /// Font `SourceSansPro-Light`.
    static let sourceSansProLight = Rswift.FontResource(fontName: "SourceSansPro-Light")
    /// Font `SourceSansPro-Regular`.
    static let sourceSansProRegular = Rswift.FontResource(fontName: "SourceSansPro-Regular")
    /// Font `SourceSansPro-SemiboldIt`.
    static let sourceSansProSemiboldIt = Rswift.FontResource(fontName: "SourceSansPro-SemiboldIt")
    /// Font `SourceSansPro-Semibold`.
    static let sourceSansProSemibold = Rswift.FontResource(fontName: "SourceSansPro-Semibold")
    
    /// `UIFont(name: "MuseoSans-100", size: ...)`
    static func museoSans100(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: museoSans100, size: size)
    }
    
    /// `UIFont(name: "MuseoSans-100Italic", size: ...)`
    static func museoSans100Italic(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: museoSans100Italic, size: size)
    }
    
    /// `UIFont(name: "MuseoSans-300", size: ...)`
    static func museoSans300(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: museoSans300, size: size)
    }
    
    /// `UIFont(name: "MuseoSans-300Italic", size: ...)`
    static func museoSans300Italic(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: museoSans300Italic, size: size)
    }
    
    /// `UIFont(name: "MuseoSans-500", size: ...)`
    static func museoSans500(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: museoSans500, size: size)
    }
    
    /// `UIFont(name: "MuseoSans-500Italic", size: ...)`
    static func museoSans500Italic(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: museoSans500Italic, size: size)
    }
    
    /// `UIFont(name: "MuseoSans-700", size: ...)`
    static func museoSans700(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: museoSans700, size: size)
    }
    
    /// `UIFont(name: "MuseoSans-700Italic", size: ...)`
    static func museoSans700Italic(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: museoSans700Italic, size: size)
    }
    
    /// `UIFont(name: "MuseoSans-900", size: ...)`
    static func museoSans900(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: museoSans900, size: size)
    }
    
    /// `UIFont(name: "MuseoSans-900Italic", size: ...)`
    static func museoSans900Italic(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: museoSans900Italic, size: size)
    }
    
    /// `UIFont(name: "Oswald-Demi-BoldItalic", size: ...)`
    static func oswaldDemiBoldItalic(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: oswaldDemiBoldItalic, size: size)
    }
    
    /// `UIFont(name: "Oswald-DemiBold", size: ...)`
    static func oswaldDemiBold(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: oswaldDemiBold, size: size)
    }
    
    /// `UIFont(name: "Oswald-Light", size: ...)`
    static func oswaldLight(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: oswaldLight, size: size)
    }
    
    /// `UIFont(name: "Oswald-LightItalic", size: ...)`
    static func oswaldLightItalic(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: oswaldLightItalic, size: size)
    }
    
    /// `UIFont(name: "Oswald-Regular", size: ...)`
    static func oswaldRegular(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: oswaldRegular, size: size)
    }
    
    /// `UIFont(name: "Oswald-RegularItalic", size: ...)`
    static func oswaldRegularItalic(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: oswaldRegularItalic, size: size)
    }
    
    /// `UIFont(name: "SourceSansPro-Black", size: ...)`
    static func sourceSansProBlack(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: sourceSansProBlack, size: size)
    }
    
    /// `UIFont(name: "SourceSansPro-BlackIt", size: ...)`
    static func sourceSansProBlackIt(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: sourceSansProBlackIt, size: size)
    }
    
    /// `UIFont(name: "SourceSansPro-Bold", size: ...)`
    static func sourceSansProBold(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: sourceSansProBold, size: size)
    }
    
    /// `UIFont(name: "SourceSansPro-BoldIt", size: ...)`
    static func sourceSansProBoldIt(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: sourceSansProBoldIt, size: size)
    }
    
    /// `UIFont(name: "SourceSansPro-ExtraLight", size: ...)`
    static func sourceSansProExtraLight(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: sourceSansProExtraLight, size: size)
    }
    
    /// `UIFont(name: "SourceSansPro-ExtraLightIt", size: ...)`
    static func sourceSansProExtraLightIt(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: sourceSansProExtraLightIt, size: size)
    }
    
    /// `UIFont(name: "SourceSansPro-It", size: ...)`
    static func sourceSansProIt(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: sourceSansProIt, size: size)
    }
    
    /// `UIFont(name: "SourceSansPro-Light", size: ...)`
    static func sourceSansProLight(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: sourceSansProLight, size: size)
    }
    
    /// `UIFont(name: "SourceSansPro-LightIt", size: ...)`
    static func sourceSansProLightIt(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: sourceSansProLightIt, size: size)
    }
    
    /// `UIFont(name: "SourceSansPro-Regular", size: ...)`
    static func sourceSansProRegular(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: sourceSansProRegular, size: size)
    }
    
    /// `UIFont(name: "SourceSansPro-Semibold", size: ...)`
    static func sourceSansProSemibold(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: sourceSansProSemibold, size: size)
    }
    
    /// `UIFont(name: "SourceSansPro-SemiboldIt", size: ...)`
    static func sourceSansProSemiboldIt(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: sourceSansProSemiboldIt, size: size)
    }
    
    static func validate() throws {
      if R.font.museoSans100(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'MuseoSans-100' could not be loaded, is 'MuseoSans-100.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.museoSans100Italic(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'MuseoSans-100Italic' could not be loaded, is 'MuseoSans-100Italic.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.museoSans300(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'MuseoSans-300' could not be loaded, is 'MuseoSans-300.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.museoSans300Italic(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'MuseoSans-300Italic' could not be loaded, is 'MuseoSans-300Italic.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.museoSans500(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'MuseoSans-500' could not be loaded, is 'MuseoSans-500.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.museoSans500Italic(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'MuseoSans-500Italic' could not be loaded, is 'MuseoSans-500Italic.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.museoSans700(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'MuseoSans-700' could not be loaded, is 'MuseoSans-700.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.museoSans700Italic(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'MuseoSans-700Italic' could not be loaded, is 'MuseoSans-700Italic.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.museoSans900(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'MuseoSans-900' could not be loaded, is 'MuseoSans-900.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.museoSans900Italic(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'MuseoSans-900Italic' could not be loaded, is 'MuseoSans-900Italic.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.oswaldDemiBoldItalic(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Oswald-Demi-BoldItalic' could not be loaded, is 'Oswald-Demi-BoldItalic.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.oswaldDemiBold(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Oswald-DemiBold' could not be loaded, is 'Oswald-DemiBold.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.oswaldLight(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Oswald-Light' could not be loaded, is 'Oswald-Light.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.oswaldLightItalic(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Oswald-LightItalic' could not be loaded, is 'Oswald-LightItalic.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.oswaldRegular(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Oswald-Regular' could not be loaded, is 'Oswald-Regular.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.oswaldRegularItalic(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Oswald-RegularItalic' could not be loaded, is 'Oswald-RegularItalic.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.sourceSansProBlack(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'SourceSansPro-Black' could not be loaded, is 'SourceSansPro-Black.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.sourceSansProBlackIt(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'SourceSansPro-BlackIt' could not be loaded, is 'SourceSansPro-BlackIt.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.sourceSansProBold(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'SourceSansPro-Bold' could not be loaded, is 'SourceSansPro-Bold.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.sourceSansProBoldIt(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'SourceSansPro-BoldIt' could not be loaded, is 'SourceSansPro-BoldIt.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.sourceSansProExtraLight(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'SourceSansPro-ExtraLight' could not be loaded, is 'SourceSansPro-ExtraLight.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.sourceSansProExtraLightIt(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'SourceSansPro-ExtraLightIt' could not be loaded, is 'SourceSansPro-ExtraLightIt.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.sourceSansProIt(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'SourceSansPro-It' could not be loaded, is 'SourceSansPro-It.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.sourceSansProLight(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'SourceSansPro-Light' could not be loaded, is 'SourceSansPro-Light.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.sourceSansProLightIt(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'SourceSansPro-LightIt' could not be loaded, is 'SourceSansPro-LightIt.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.sourceSansProRegular(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'SourceSansPro-Regular' could not be loaded, is 'SourceSansPro-Regular.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.sourceSansProSemibold(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'SourceSansPro-Semibold' could not be loaded, is 'SourceSansPro-Semibold.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.sourceSansProSemiboldIt(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'SourceSansPro-SemiboldIt' could not be loaded, is 'SourceSansPro-SemiboldIt.otf' added to the UIAppFonts array in this targets Info.plist?") }
    }
    
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 3 images.
  struct image {
    /// Image `music.note.list`.
    static let musicNoteList = Rswift.ImageResource(bundle: R.hostingBundle, name: "music.note.list")
    /// Image `play.fill`.
    static let playFill = Rswift.ImageResource(bundle: R.hostingBundle, name: "play.fill")
    /// Image `play`.
    static let play = Rswift.ImageResource(bundle: R.hostingBundle, name: "play")
    
    /// `UIImage(named: "music.note.list", bundle: ..., traitCollection: ...)`
    static func musicNoteList(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.musicNoteList, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "play", bundle: ..., traitCollection: ...)`
    static func play(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.play, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "play.fill", bundle: ..., traitCollection: ...)`
    static func playFill(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.playFill, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 1 nibs.
  struct nib {
    /// Nib `PageCollectionViewCell`.
    static let pageCollectionViewCell = _R.nib._PageCollectionViewCell()
    
    /// `UINib(name: "PageCollectionViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.pageCollectionViewCell) instead")
    static func pageCollectionViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.pageCollectionViewCell)
    }
    
    static func pageCollectionViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> PageCollectionViewCell? {
      return R.nib.pageCollectionViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? PageCollectionViewCell
    }
    
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 4 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `PageCell`.
    static let pageCell: Rswift.ReuseIdentifier<PageCell> = Rswift.ReuseIdentifier(identifier: "PageCell")
    /// Reuse identifier `PageCollectionViewCell`.
    static let pageCollectionViewCell: Rswift.ReuseIdentifier<PageCollectionViewCell> = Rswift.ReuseIdentifier(identifier: "PageCollectionViewCell")
    /// Reuse identifier `SongSelectCell`.
    static let songSelectCell: Rswift.ReuseIdentifier<SongSelectCell> = Rswift.ReuseIdentifier(identifier: "SongSelectCell")
    /// Reuse identifier `challengeCellId`.
    static let challengeCellId: Rswift.ReuseIdentifier<ChallengeCell> = Rswift.ReuseIdentifier(identifier: "challengeCellId")
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 10 storyboards.
  struct storyboard {
    /// Storyboard `Alert`.
    static let alert = _R.storyboard.alert()
    /// Storyboard `CreateChallenge`.
    static let createChallenge = _R.storyboard.createChallenge()
    /// Storyboard `CurrentChallenge`.
    static let currentChallenge = _R.storyboard.currentChallenge()
    /// Storyboard `Guide`.
    static let guide = _R.storyboard.guide()
    /// Storyboard `History`.
    static let history = _R.storyboard.history()
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Losing`.
    static let losing = _R.storyboard.losing()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    /// Storyboard `PageNavigation`.
    static let pageNavigation = _R.storyboard.pageNavigation()
    /// Storyboard `Settings`.
    static let settings = _R.storyboard.settings()
    
    /// `UIStoryboard(name: "Alert", bundle: ...)`
    static func alert(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.alert)
    }
    
    /// `UIStoryboard(name: "CreateChallenge", bundle: ...)`
    static func createChallenge(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.createChallenge)
    }
    
    /// `UIStoryboard(name: "CurrentChallenge", bundle: ...)`
    static func currentChallenge(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.currentChallenge)
    }
    
    /// `UIStoryboard(name: "Guide", bundle: ...)`
    static func guide(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.guide)
    }
    
    /// `UIStoryboard(name: "History", bundle: ...)`
    static func history(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.history)
    }
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Losing", bundle: ...)`
    static func losing(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.losing)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    /// `UIStoryboard(name: "PageNavigation", bundle: ...)`
    static func pageNavigation(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.pageNavigation)
    }
    
    /// `UIStoryboard(name: "Settings", bundle: ...)`
    static func settings(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.settings)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 3 localization tables.
  struct string {
    /// This `R.string.launchScreen` struct is generated, and contains static references to 0 localization keys.
    struct launchScreen {
      fileprivate init() {}
    }
    
    /// This `R.string.localizable` struct is generated, and contains static references to 21 localization keys.
    struct localizable {
      /// en translation: %#@value@
      /// 
      /// Locales: en, ru
      static let timerMinLeft = Rswift.StringResource(key: "timer.minLeft", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// ru translation: 1. Установите время испытания.  2. Выберите режим и сделайте вашу ставку. Деньги или время значительно увеличат вашу мотивацию!  3. Следуйте главному правилу — не покидайте приложение. Блокировать экран можно.
      /// 
      /// Locales: ru, en
      static let guideSecondPageContent = Rswift.StringResource(key: "guide.secondPage.content", tableName: "Localizable", bundle: R.hostingBundle, locales: ["ru", "en"], comment: nil)
      /// ru translation: Distant Place
      /// 
      /// Locales: ru, en
      static let songNamesDistantPlace = Rswift.StringResource(key: "songNames.distantPlace", tableName: "Localizable", bundle: R.hostingBundle, locales: ["ru", "en"], comment: nil)
      /// ru translation: Floating Point
      /// 
      /// Locales: ru, en
      static let songNamesFloatingPoint = Rswift.StringResource(key: "songNames.floatingPoint", tableName: "Localizable", bundle: R.hostingBundle, locales: ["ru", "en"], comment: nil)
      /// ru translation: Leaving Wonderland
      /// 
      /// Locales: ru, en
      static let songNamesLeavingWonderland = Rswift.StringResource(key: "songNames.leavingWonderland", tableName: "Localizable", bundle: R.hostingBundle, locales: ["ru", "en"], comment: nil)
      /// ru translation: Long Days
      /// 
      /// Locales: ru, en
      static let songNamesLongDays = Rswift.StringResource(key: "songNames.longDays", tableName: "Localizable", bundle: R.hostingBundle, locales: ["ru", "en"], comment: nil)
      /// ru translation: Metting The Sun
      /// 
      /// Locales: ru, en
      static let songNamesMettingSun = Rswift.StringResource(key: "songNames.mettingSun", tableName: "Localizable", bundle: R.hostingBundle, locales: ["ru", "en"], comment: nil)
      /// ru translation: Pillow Talk
      /// 
      /// Locales: ru, en
      static let songNamesPillowTalk = Rswift.StringResource(key: "songNames.pillowTalk", tableName: "Localizable", bundle: R.hostingBundle, locales: ["ru", "en"], comment: nil)
      /// ru translation: Ваша задача требует концентрации?
      /// 
      /// Locales: ru, en
      static let guideSecondPageTitle = Rswift.StringResource(key: "guide.secondPage.title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["ru", "en"], comment: nil)
      /// ru translation: Вы проиграете в текущем испытании, если не вернетесь в приложение!
      /// 
      /// Locales: ru, en
      static let notificationsReturnBody = Rswift.StringResource(key: "notifications.return.body", tableName: "Localizable", bundle: R.hostingBundle, locales: ["ru", "en"], comment: nil)
      /// ru translation: Далее
      /// 
      /// Locales: ru, en
      static let guideNext = Rswift.StringResource(key: "guide.next", tableName: "Localizable", bundle: R.hostingBundle, locales: ["ru", "en"], comment: nil)
      /// ru translation: Для того, чтобы разблокировать приложение Вам необходимо совершить покупку на сумму равную вашей ставке
      /// 
      /// Locales: ru, en
      static let purchaseLoseMessage = Rswift.StringResource(key: "purchase.loseMessage", tableName: "Localizable", bundle: R.hostingBundle, locales: ["ru", "en"], comment: nil)
      /// ru translation: Локализованная строка
      /// 
      /// Locales: ru, en
      static let alertExample = Rswift.StringResource(key: "alert.example", tableName: "Localizable", bundle: R.hostingBundle, locales: ["ru", "en"], comment: nil)
      /// ru translation: Нажмите, чтобы не проиграть!
      /// 
      /// Locales: ru, en
      static let notificationsReturnTitle = Rswift.StringResource(key: "notifications.return.title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["ru", "en"], comment: nil)
      /// ru translation: Начните испытание!
      /// 
      /// Locales: ru, en
      static let guideThirdPageTitle = Rswift.StringResource(key: "guide.thirdPage.title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["ru", "en"], comment: nil)
      /// ru translation: Понятно!
      /// 
      /// Locales: ru, en
      static let guideGotIt = Rswift.StringResource(key: "guide.gotIt", tableName: "Localizable", bundle: R.hostingBundle, locales: ["ru", "en"], comment: nil)
      /// ru translation: Привет!
      /// 
      /// Locales: ru, en
      static let guideFirstPageTitle = Rswift.StringResource(key: "guide.firstPage.title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["ru", "en"], comment: nil)
      /// ru translation: Пропустить
      /// 
      /// Locales: ru, en
      static let guideSkip = Rswift.StringResource(key: "guide.skip", tableName: "Localizable", bundle: R.hostingBundle, locales: ["ru", "en"], comment: nil)
      /// ru translation: Разблокировать
      /// 
      /// Locales: ru, en
      static let purchaseButtonTitle = Rswift.StringResource(key: "purchase.buttonTitle", tableName: "Localizable", bundle: R.hostingBundle, locales: ["ru", "en"], comment: nil)
      /// ru translation: Соблюдайте правила, сфокусируйтесь на вашей цели и помните, время — деньги, и вы можете их потерять!
      /// 
      /// Locales: ru, en
      static let guideThirdPageContent = Rswift.StringResource(key: "guide.thirdPage.content", tableName: "Localizable", bundle: R.hostingBundle, locales: ["ru", "en"], comment: nil)
      /// ru translation: Это приложение поможет вам сфокусироваться на важных задачах, не отвлекаясь на социальные сети, мессенджеры и игры.  Для достижения этой цели мы прелагаем вам испытание, ставкой в котором будет ваше время или деньги!
      /// 
      /// Locales: ru, en
      static let guideFirstPageContent = Rswift.StringResource(key: "guide.firstPage.content", tableName: "Localizable", bundle: R.hostingBundle, locales: ["ru", "en"], comment: nil)
      
      /// en translation: %#@value@
      /// 
      /// Locales: en, ru
      static func timerMinLeft(value value1: Int) -> String {
        return String(format: NSLocalizedString("timer.minLeft", bundle: R.hostingBundle, comment: ""), locale: R.applicationLocale, value1)
      }
      
      /// ru translation: 1. Установите время испытания.  2. Выберите режим и сделайте вашу ставку. Деньги или время значительно увеличат вашу мотивацию!  3. Следуйте главному правилу — не покидайте приложение. Блокировать экран можно.
      /// 
      /// Locales: ru, en
      static func guideSecondPageContent(_: Void = ()) -> String {
        return NSLocalizedString("guide.secondPage.content", bundle: R.hostingBundle, comment: "")
      }
      
      /// ru translation: Distant Place
      /// 
      /// Locales: ru, en
      static func songNamesDistantPlace(_: Void = ()) -> String {
        return NSLocalizedString("songNames.distantPlace", bundle: R.hostingBundle, comment: "")
      }
      
      /// ru translation: Floating Point
      /// 
      /// Locales: ru, en
      static func songNamesFloatingPoint(_: Void = ()) -> String {
        return NSLocalizedString("songNames.floatingPoint", bundle: R.hostingBundle, comment: "")
      }
      
      /// ru translation: Leaving Wonderland
      /// 
      /// Locales: ru, en
      static func songNamesLeavingWonderland(_: Void = ()) -> String {
        return NSLocalizedString("songNames.leavingWonderland", bundle: R.hostingBundle, comment: "")
      }
      
      /// ru translation: Long Days
      /// 
      /// Locales: ru, en
      static func songNamesLongDays(_: Void = ()) -> String {
        return NSLocalizedString("songNames.longDays", bundle: R.hostingBundle, comment: "")
      }
      
      /// ru translation: Metting The Sun
      /// 
      /// Locales: ru, en
      static func songNamesMettingSun(_: Void = ()) -> String {
        return NSLocalizedString("songNames.mettingSun", bundle: R.hostingBundle, comment: "")
      }
      
      /// ru translation: Pillow Talk
      /// 
      /// Locales: ru, en
      static func songNamesPillowTalk(_: Void = ()) -> String {
        return NSLocalizedString("songNames.pillowTalk", bundle: R.hostingBundle, comment: "")
      }
      
      /// ru translation: Ваша задача требует концентрации?
      /// 
      /// Locales: ru, en
      static func guideSecondPageTitle(_: Void = ()) -> String {
        return NSLocalizedString("guide.secondPage.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// ru translation: Вы проиграете в текущем испытании, если не вернетесь в приложение!
      /// 
      /// Locales: ru, en
      static func notificationsReturnBody(_: Void = ()) -> String {
        return NSLocalizedString("notifications.return.body", bundle: R.hostingBundle, comment: "")
      }
      
      /// ru translation: Далее
      /// 
      /// Locales: ru, en
      static func guideNext(_: Void = ()) -> String {
        return NSLocalizedString("guide.next", bundle: R.hostingBundle, comment: "")
      }
      
      /// ru translation: Для того, чтобы разблокировать приложение Вам необходимо совершить покупку на сумму равную вашей ставке
      /// 
      /// Locales: ru, en
      static func purchaseLoseMessage(_: Void = ()) -> String {
        return NSLocalizedString("purchase.loseMessage", bundle: R.hostingBundle, comment: "")
      }
      
      /// ru translation: Локализованная строка
      /// 
      /// Locales: ru, en
      static func alertExample(_: Void = ()) -> String {
        return NSLocalizedString("alert.example", bundle: R.hostingBundle, comment: "")
      }
      
      /// ru translation: Нажмите, чтобы не проиграть!
      /// 
      /// Locales: ru, en
      static func notificationsReturnTitle(_: Void = ()) -> String {
        return NSLocalizedString("notifications.return.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// ru translation: Начните испытание!
      /// 
      /// Locales: ru, en
      static func guideThirdPageTitle(_: Void = ()) -> String {
        return NSLocalizedString("guide.thirdPage.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// ru translation: Понятно!
      /// 
      /// Locales: ru, en
      static func guideGotIt(_: Void = ()) -> String {
        return NSLocalizedString("guide.gotIt", bundle: R.hostingBundle, comment: "")
      }
      
      /// ru translation: Привет!
      /// 
      /// Locales: ru, en
      static func guideFirstPageTitle(_: Void = ()) -> String {
        return NSLocalizedString("guide.firstPage.title", bundle: R.hostingBundle, comment: "")
      }
      
      /// ru translation: Пропустить
      /// 
      /// Locales: ru, en
      static func guideSkip(_: Void = ()) -> String {
        return NSLocalizedString("guide.skip", bundle: R.hostingBundle, comment: "")
      }
      
      /// ru translation: Разблокировать
      /// 
      /// Locales: ru, en
      static func purchaseButtonTitle(_: Void = ()) -> String {
        return NSLocalizedString("purchase.buttonTitle", bundle: R.hostingBundle, comment: "")
      }
      
      /// ru translation: Соблюдайте правила, сфокусируйтесь на вашей цели и помните, время — деньги, и вы можете их потерять!
      /// 
      /// Locales: ru, en
      static func guideThirdPageContent(_: Void = ()) -> String {
        return NSLocalizedString("guide.thirdPage.content", bundle: R.hostingBundle, comment: "")
      }
      
      /// ru translation: Это приложение поможет вам сфокусироваться на важных задачах, не отвлекаясь на социальные сети, мессенджеры и игры.  Для достижения этой цели мы прелагаем вам испытание, ставкой в котором будет ваше время или деньги!
      /// 
      /// Locales: ru, en
      static func guideFirstPageContent(_: Void = ()) -> String {
        return NSLocalizedString("guide.firstPage.content", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    /// This `R.string.main` struct is generated, and contains static references to 1 localization keys.
    struct main {
      /// ru translation: Action
      /// 
      /// Locales: ru
      static let bOR9iWUYNormalTitle = Rswift.StringResource(key: "bOR-9i-wUY.normalTitle", tableName: "Main", bundle: R.hostingBundle, locales: ["ru"], comment: nil)
      
      /// ru translation: Action
      /// 
      /// Locales: ru
      static func bOR9iWUYNormalTitle(_: Void = ()) -> String {
        return NSLocalizedString("bOR-9i-wUY.normalTitle", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
    try nib.validate()
  }
  
  struct nib: Rswift.Validatable {
    static func validate() throws {
      try _PageCollectionViewCell.validate()
    }
    
    struct _PageCollectionViewCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType, Rswift.Validatable {
      typealias ReusableType = PageCollectionViewCell
      
      let bundle = R.hostingBundle
      let identifier = "PageCollectionViewCell"
      let name = "PageCollectionViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> PageCollectionViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? PageCollectionViewCell
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "testIcon", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'testIcon' is used in nib 'PageCollectionViewCell', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
          if UIKit.UIColor(named: "CTBlack", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'CTBlack' is used in storyboard 'PageCollectionViewCell', but couldn't be loaded.") }
        }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try alert.validate()
      try createChallenge.validate()
      try currentChallenge.validate()
      try guide.validate()
      try history.validate()
      try launchScreen.validate()
      try losing.validate()
      try main.validate()
      try pageNavigation.validate()
      try settings.validate()
    }
    
    struct alert: Rswift.StoryboardResourceType, Rswift.Validatable {
      let alertViewController = StoryboardViewControllerResource<AlertViewController>(identifier: "AlertViewController")
      let bundle = R.hostingBundle
      let name = "Alert"
      
      func alertViewController(_: Void = ()) -> AlertViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: alertViewController)
      }
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
        if _R.storyboard.alert().alertViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'alertViewController' could not be loaded from storyboard 'Alert' as 'AlertViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct createChallenge: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let createChallengeViewController = StoryboardViewControllerResource<CreateChallengeViewController>(identifier: "CreateChallengeViewController")
      let name = "CreateChallenge"
      
      func createChallengeViewController(_: Void = ()) -> CreateChallengeViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: createChallengeViewController)
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "testIcon", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'testIcon' is used in storyboard 'CreateChallenge', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
          if UIKit.UIColor(named: "AppColor", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'AppColor' is used in storyboard 'CreateChallenge', but couldn't be loaded.") }
          if UIKit.UIColor(named: "CTOrange", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'CTOrange' is used in storyboard 'CreateChallenge', but couldn't be loaded.") }
          if UIKit.UIColor(named: "CTWhite", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'CTWhite' is used in storyboard 'CreateChallenge', but couldn't be loaded.") }
        }
        if _R.storyboard.createChallenge().createChallengeViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'createChallengeViewController' could not be loaded from storyboard 'CreateChallenge' as 'CreateChallengeViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct currentChallenge: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let currentChallengeViewController = StoryboardViewControllerResource<CurrentChallengeViewController>(identifier: "CurrentChallengeViewController")
      let name = "CurrentChallenge"
      
      func currentChallengeViewController(_: Void = ()) -> CurrentChallengeViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: currentChallengeViewController)
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "music.note.list", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'music.note.list' is used in storyboard 'CurrentChallenge', but couldn't be loaded.") }
        if UIKit.UIImage(named: "play", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'play' is used in storyboard 'CurrentChallenge', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
          if UIKit.UIColor(named: "CTOrange", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'CTOrange' is used in storyboard 'CurrentChallenge', but couldn't be loaded.") }
          if UIKit.UIColor(named: "CTWhite", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'CTWhite' is used in storyboard 'CurrentChallenge', but couldn't be loaded.") }
        }
        if _R.storyboard.currentChallenge().currentChallengeViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'currentChallengeViewController' could not be loaded from storyboard 'CurrentChallenge' as 'CurrentChallengeViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct guide: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let guideViewController = StoryboardViewControllerResource<GuideViewController>(identifier: "GuideViewController")
      let name = "Guide"
      
      func guideViewController(_: Void = ()) -> GuideViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: guideViewController)
      }
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
          if UIKit.UIColor(named: "CTGray", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'CTGray' is used in storyboard 'Guide', but couldn't be loaded.") }
          if UIKit.UIColor(named: "CTOrange", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'CTOrange' is used in storyboard 'Guide', but couldn't be loaded.") }
        }
        if _R.storyboard.guide().guideViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'guideViewController' could not be loaded from storyboard 'Guide' as 'GuideViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct history: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let historyViewController = StoryboardViewControllerResource<HistoryViewController>(identifier: "HistoryViewController")
      let name = "History"
      
      func historyViewController(_: Void = ()) -> HistoryViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: historyViewController)
      }
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
          if UIKit.UIColor(named: "CTWhite", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'CTWhite' is used in storyboard 'History', but couldn't be loaded.") }
        }
        if _R.storyboard.history().historyViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'historyViewController' could not be loaded from storyboard 'History' as 'HistoryViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct losing: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let losingViewController = StoryboardViewControllerResource<LosingViewController>(identifier: "LosingViewController")
      let name = "Losing"
      
      func losingViewController(_: Void = ()) -> LosingViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: losingViewController)
      }
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
          if UIKit.UIColor(named: "CTWhite", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'CTWhite' is used in storyboard 'Losing', but couldn't be loaded.") }
        }
        if _R.storyboard.losing().losingViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'losingViewController' could not be loaded from storyboard 'Losing' as 'LosingViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let mainViewController = StoryboardViewControllerResource<MainViewController>(identifier: "MainViewController")
      let name = "Main"
      
      func mainViewController(_: Void = ()) -> MainViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: mainViewController)
      }
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
        if _R.storyboard.main().mainViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'mainViewController' could not be loaded from storyboard 'Main' as 'MainViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct pageNavigation: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "PageNavigation"
      let pageNavigationViewController = StoryboardViewControllerResource<PageNavigationViewController>(identifier: "PageNavigationViewController")
      
      func pageNavigationViewController(_: Void = ()) -> PageNavigationViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: pageNavigationViewController)
      }
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
          if UIKit.UIColor(named: "CTWhite", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'CTWhite' is used in storyboard 'PageNavigation', but couldn't be loaded.") }
        }
        if _R.storyboard.pageNavigation().pageNavigationViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'pageNavigationViewController' could not be loaded from storyboard 'PageNavigation' as 'PageNavigationViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct settings: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let musicSelectViewController = StoryboardViewControllerResource<MusicSelectViewController>(identifier: "MusicSelectViewController")
      let name = "Settings"
      let settingsViewController = StoryboardViewControllerResource<SettingsViewController>(identifier: "SettingsViewController")
      
      func musicSelectViewController(_: Void = ()) -> MusicSelectViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: musicSelectViewController)
      }
      
      func settingsViewController(_: Void = ()) -> SettingsViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: settingsViewController)
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "play", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'play' is used in storyboard 'Settings', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
          if UIKit.UIColor(named: "CTBlack", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'CTBlack' is used in storyboard 'Settings', but couldn't be loaded.") }
          if UIKit.UIColor(named: "CTGray", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'CTGray' is used in storyboard 'Settings', but couldn't be loaded.") }
          if UIKit.UIColor(named: "CTOrange", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'CTOrange' is used in storyboard 'Settings', but couldn't be loaded.") }
          if UIKit.UIColor(named: "CTWhite", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'CTWhite' is used in storyboard 'Settings', but couldn't be loaded.") }
        }
        if _R.storyboard.settings().musicSelectViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'musicSelectViewController' could not be loaded from storyboard 'Settings' as 'MusicSelectViewController'.") }
        if _R.storyboard.settings().settingsViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'settingsViewController' could not be loaded from storyboard 'Settings' as 'SettingsViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
